# Generated by Django 5.1.2 on 2025-10-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_photo_likes_count_photolike'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.CharField(choices=[('weddings', 'Weddings & Related Events'), ('family', 'Family & Life Milestones'), ('celebrations', 'Celebrations & Parties'), ('travel', 'Travel & Adventures'), ('special', 'Special Events & Occasions'), ('personal', 'Personal & Creative Albums')], default='weddings', max_length=20),
        ),
    ]
