# Generated by Django 5.1.2 on 2025-10-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_album_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='allow_downloads',
            field=models.BooleanField(default=True),
        ),
    ]
