# Generated by Django 5.1.2 on 2025-10-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_album_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='medium_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='category',
            field=models.CharField(choices=[('weddings', 'Weddings & Related Events'), ('family', 'Family & Life Milestones'), ('celebrations', 'Celebrations & Parties'), ('travel', 'Travel & Adventures'), ('special', 'Special Events & Occasions'), ('personal', 'Personal & Creative Albums')], db_index=True, default='weddings', max_length=20),
        ),
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='names',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['album', 'order'], name='albums_phot_album_i_3c836d_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['album', '-likes_count'], name='albums_phot_album_i_ab55b9_idx'),
        ),
        migrations.AddIndex(
            model_name='photolike',
            index=models.Index(fields=['photo', 'ip_address'], name='albums_phot_photo_i_586d1e_idx'),
        ),
    ]
