# Generated by Django 5.1.2 on 2025-12-18 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_mediaitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=20)),
                ('icon', models.CharField(default='FiUsers', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='albums.studiocontent')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
